services:
  - type: web
    name: analyze-image-api
    env: python
    buildCommand: ""
    startCommand: gunicorn -w 1 -b 0.0.0.0:5000 analyze_image:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
