services:
  - type: web
    name: analyze-image-api
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn analyze_image:app --workers=1 --timeout=120 --bind=0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
